### ISSUE TITLE
Malformed command while initializing new project under Windows

### ISSUE THREAD

**Issue by cadabrum** [angel-dart/cli#56]
PS D:\DartProjects> C:\Users\user\AppData\Roaming\Pub\Cache\bin\angel init test
Checking for update... No update available.
Creating new Angel project in D:\DartProjects\test...
Cloning into 'D:\DartProjects\test'...
Generated new development JWT secret: 033tr16cyK131yK85245x647qlrwUas5
Generated new production JWT secret: ipXBevnXPiSVfQPoSBLHMeLvDH2RhVfu
Renaming project from "angel" to "test"...
Changing MongoDB URL in file "D:\DartProjects\test\config\default.yaml"...
Renaming library file `D:\DartProjects\test\lib\angel.dart`...
Updated file `D:\DartProjects\test\bin\cluster.dart`.
Updated file `D:\DartProjects\test\bin\common.dart`.
Updated file `D:\DartProjects\test\bin\multi_server.dart`.
Updated file `D:\DartProjects\test\lib\src\config\config.dart`.
Updated file `D:\DartProjects\test\lib\src\config\plugins\plugins.dart`.
Updated file `D:\DartProjects\test\lib\src\models\models.dart`.
Updated file `D:\DartProjects\test\lib\src\models\user.dart`.
Updated file `D:\DartProjects\test\lib\src\routes\controllers\auth.dart`.
Updated file `D:\DartProjects\test\lib\src\routes\controllers\controllers.dart`.
Updated file `D:\DartProjects\test\lib\src\routes\routes.dart`.
Updated file `D:\DartProjects\test\lib\src\services\services.dart`.
Updated file `D:\DartProjects\test\lib\test.dart`.
Updated file `D:\DartProjects\test\test\services\users_test.dart`.
Now running pub get...
Running pub at "/D:/Dart/dart-sdk/bin/pub"...
Oops, something went wrong: ProcessException: File not found.

  Command: /D:/Dart/dart-sdk/bin/pub get

**Comment by thosakwe** [comment]
Can you verify that pub exists at the shown path? I think I will have to append a ".bat" on Windows systems.

Your project is initialized, though, which is the good news. You can run pub get yourself, until I patch this. Sorry for the inconvenience!

**Comment by cadabrum** [comment]
The main problem here is leading "/" which breaks command execution. Windows can run *.bat files in PATH enviroment without specifying extension part.

**Comment by thosakwe** [comment]
Ah, I see. Thank you - I will fix and close this once I am home.

**Comment by thosakwe** [comment]
What went wrong is that instead of calling `toFilePath` on the Pub URI, I
just used `path`:
https://github.com/angel-dart/cli/blob/master/lib/src/commands/init.dart#L145

I have to test this patch on Windows.

**Comment by thosakwe** [comment]
About to push a commit that resolves this. Thanks!!!

**Comment by pjcunningham** [comment]
This isn't working in version 1.0.11. As you mentioned above you need to append '.bat' on Windows systems. Here's a snippet that prints out the pub version that successfully runs on Windows:

```
import "dart:io";

main(List<String> arguments) async {

  var exec = new File(Platform.resolvedExecutable);

  var pubFile = (Platform.isWindows) ? 'pub.bat' : 'pub';
  var pubPath = exec.parent.uri.resolve(pubFile).toFilePath();

  print('Running pub at "$pubPath"...');
  var pub = await Process.start(pubPath, ["version"]);
  stdout.addStream(pub.stdout);
  stderr.addStream(pub.stderr);
  var code = await pub.exitCode;
  print("Pub process exited with code $code");
}
```
Output:
```
Running pub at "D:\Dart\dart-sdk\bin\pub.bat"...
Pub 1.23.0
Pub process exited with code 0
```

**Comment by thosakwe** [comment]
Thanks! I'm using a Windows machine these days, so I should be able to fix
it soon.

In the meantime, manually run "pub get" yourself. Sorry for the
inconvenience!

**Comment by thosakwe** [comment]
@pjcunningham Should be taken care of now!
