### ISSUE TITLE
Angel CLI user input windows 10

### ISSUE THREAD

**Issue by massimoliani** [angel-dart/cli#92]
I start to learn angel (greta job!) I download angel_cli and try to make new project.
In windows 10 using powershell or cmd (cmd is better as microsoft include pub command not compatible with traditional pub app) I can't select the project type.
I'm using VSCODE with flutter web installation, flutter bring dart compiler so I didn't install any dart compiler or dart extension.
I tries to make an angel app yesterday, following your guide, and it run correctly.

This is the screenshot:
k:\PROJECTS\ANGEL>angel init hello2
Creating new Angel project in k:\PROJECTS\ANGEL\hello2...
✔ Directory 'k:\PROJECTS\ANGEL\hello2' already exists. Overwrite it? (y/N) ‥ y
Choose a project type before continuing:
Choose a project type before continuing:

* Basic (Minimal starting point for Angel 2.x - A simple server with only a few additional packages.)
ORM (A starting point for applications that use Angel's ORM.)
GraphQL (A starting point for GraphQL API servers.)
Shared (Holds common models and files shared across multiple Dart projects.)
Shared (ORM) (Holds common models and files shared across multiple Dart projects.)

No way to select, any typed characters can't work.

Thank you for your help.

**Comment by tristian-me** [comment]
I have a fix for this; the problem relates to the *prompts* package that Angel relies on. I will add the fix and hopefully @thosakwe will accept the fix.

**Comment by thosakwe** [comment]
Fixed in https://github.com/thosakwe/prompts/pull/3!
